# coding: utf-8

"""
    Stargate SRM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_acheivement_options_acheivement_options_get(self):
        """Test case for api_acheivement_options_acheivement_options_get

        """
        pass

    def test_api_acheivement_options_acheivement_options_options(self):
        """Test case for api_acheivement_options_acheivement_options_options

        """
        pass

    def test_api_acheivement_options_get(self):
        """Test case for api_acheivement_options_get

        """
        pass

    def test_api_acheivement_options_options(self):
        """Test case for api_acheivement_options_options

        """
        pass

    def test_api_acheivement_options_post(self):
        """Test case for api_acheivement_options_post

        """
        pass

    def test_api_add_milestone_attachment_options(self):
        """Test case for api_add_milestone_attachment_options

        """
        pass

    def test_api_add_milestone_attachment_post(self):
        """Test case for api_add_milestone_attachment_post

        """
        pass

    def test_api_business_partner_get_applied_jobs_jobs_uuid_get(self):
        """Test case for api_business_partner_get_applied_jobs_jobs_uuid_get

        """
        pass

    def test_api_business_partner_get_applied_jobs_jobs_uuid_options(self):
        """Test case for api_business_partner_get_applied_jobs_jobs_uuid_options

        """
        pass

    def test_api_business_partner_get_signedup_programs_program_uuid_get(self):
        """Test case for api_business_partner_get_signedup_programs_program_uuid_get

        """
        pass

    def test_api_business_partner_get_signedup_programs_program_uuid_options(self):
        """Test case for api_business_partner_get_signedup_programs_program_uuid_options

        """
        pass

    def test_api_business_partner_jobs_apply_business_partner_job_id_delete(self):
        """Test case for api_business_partner_jobs_apply_business_partner_job_id_delete

        """
        pass

    def test_api_business_partner_jobs_apply_business_partner_job_id_options(self):
        """Test case for api_business_partner_jobs_apply_business_partner_job_id_options

        """
        pass

    def test_api_business_partner_jobs_apply_get(self):
        """Test case for api_business_partner_jobs_apply_get

        """
        pass

    def test_api_business_partner_jobs_apply_options(self):
        """Test case for api_business_partner_jobs_apply_options

        """
        pass

    def test_api_business_partner_jobs_apply_post(self):
        """Test case for api_business_partner_jobs_apply_post

        """
        pass

    def test_api_business_partner_jobs_get(self):
        """Test case for api_business_partner_jobs_get

        """
        pass

    def test_api_business_partner_jobs_jobs_uuid_delete(self):
        """Test case for api_business_partner_jobs_jobs_uuid_delete

        """
        pass

    def test_api_business_partner_jobs_jobs_uuid_get(self):
        """Test case for api_business_partner_jobs_jobs_uuid_get

        """
        pass

    def test_api_business_partner_jobs_jobs_uuid_options(self):
        """Test case for api_business_partner_jobs_jobs_uuid_options

        """
        pass

    def test_api_business_partner_jobs_jobs_uuid_patch(self):
        """Test case for api_business_partner_jobs_jobs_uuid_patch

        """
        pass

    def test_api_business_partner_jobs_jobs_uuid_put(self):
        """Test case for api_business_partner_jobs_jobs_uuid_put

        """
        pass

    def test_api_business_partner_jobs_options(self):
        """Test case for api_business_partner_jobs_options

        """
        pass

    def test_api_business_partner_jobs_post(self):
        """Test case for api_business_partner_jobs_post

        """
        pass

    def test_api_business_partner_jobs_send_message_options(self):
        """Test case for api_business_partner_jobs_send_message_options

        """
        pass

    def test_api_business_partner_jobs_send_message_post(self):
        """Test case for api_business_partner_jobs_send_message_post

        """
        pass

    def test_api_business_partner_program_get(self):
        """Test case for api_business_partner_program_get

        """
        pass

    def test_api_business_partner_program_options(self):
        """Test case for api_business_partner_program_options

        """
        pass

    def test_api_business_partner_program_post(self):
        """Test case for api_business_partner_program_post

        """
        pass

    def test_api_business_partner_program_program_uuid_delete(self):
        """Test case for api_business_partner_program_program_uuid_delete

        """
        pass

    def test_api_business_partner_program_program_uuid_get(self):
        """Test case for api_business_partner_program_program_uuid_get

        """
        pass

    def test_api_business_partner_program_program_uuid_options(self):
        """Test case for api_business_partner_program_program_uuid_options

        """
        pass

    def test_api_business_partner_program_program_uuid_patch(self):
        """Test case for api_business_partner_program_program_uuid_patch

        """
        pass

    def test_api_business_partner_program_program_uuid_put(self):
        """Test case for api_business_partner_program_program_uuid_put

        """
        pass

    def test_api_business_partner_program_send_message_options(self):
        """Test case for api_business_partner_program_send_message_options

        """
        pass

    def test_api_business_partner_program_send_message_post(self):
        """Test case for api_business_partner_program_send_message_post

        """
        pass

    def test_api_business_partner_program_sign_up_get(self):
        """Test case for api_business_partner_program_sign_up_get

        """
        pass

    def test_api_business_partner_program_sign_up_options(self):
        """Test case for api_business_partner_program_sign_up_options

        """
        pass

    def test_api_business_partner_program_sign_up_post(self):
        """Test case for api_business_partner_program_sign_up_post

        """
        pass

    def test_api_business_partner_program_sign_up_program_uuid_delete(self):
        """Test case for api_business_partner_program_sign_up_program_uuid_delete

        """
        pass

    def test_api_business_partner_program_sign_up_program_uuid_options(self):
        """Test case for api_business_partner_program_sign_up_program_uuid_options

        """
        pass

    def test_api_business_partner_user_business_partner_uuid_delete(self):
        """Test case for api_business_partner_user_business_partner_uuid_delete

        """
        pass

    def test_api_business_partner_user_business_partner_uuid_get(self):
        """Test case for api_business_partner_user_business_partner_uuid_get

        """
        pass

    def test_api_business_partner_user_business_partner_uuid_options(self):
        """Test case for api_business_partner_user_business_partner_uuid_options

        """
        pass

    def test_api_business_partner_user_business_partner_uuid_patch(self):
        """Test case for api_business_partner_user_business_partner_uuid_patch

        """
        pass

    def test_api_business_partner_user_business_partner_uuid_put(self):
        """Test case for api_business_partner_user_business_partner_uuid_put

        """
        pass

    def test_api_business_partner_user_get(self):
        """Test case for api_business_partner_user_get

        """
        pass

    def test_api_business_partner_user_options(self):
        """Test case for api_business_partner_user_options

        """
        pass

    def test_api_business_partner_user_post(self):
        """Test case for api_business_partner_user_post

        """
        pass

    def test_api_career_path_get(self):
        """Test case for api_career_path_get

        """
        pass

    def test_api_career_path_options(self):
        """Test case for api_career_path_options

        """
        pass

    def test_api_career_path_post(self):
        """Test case for api_career_path_post

        """
        pass

    def test_api_cluster_get(self):
        """Test case for api_cluster_get

        """
        pass

    def test_api_cluster_options(self):
        """Test case for api_cluster_options

        """
        pass

    def test_api_cluster_post(self):
        """Test case for api_cluster_post

        """
        pass

    def test_api_cluster_type_get(self):
        """Test case for api_cluster_type_get

        """
        pass

    def test_api_cluster_type_options(self):
        """Test case for api_cluster_type_options

        """
        pass

    def test_api_cluster_type_post(self):
        """Test case for api_cluster_type_post

        """
        pass

    def test_api_college_program_list_get(self):
        """Test case for api_college_program_list_get

        """
        pass

    def test_api_college_program_list_options(self):
        """Test case for api_college_program_list_options

        """
        pass

    def test_api_collegepath_search_get(self):
        """Test case for api_collegepath_search_get

        """
        pass

    def test_api_collegepath_search_options(self):
        """Test case for api_collegepath_search_options

        """
        pass

    def test_api_compare_paths_options(self):
        """Test case for api_compare_paths_options

        """
        pass

    def test_api_compare_paths_post(self):
        """Test case for api_compare_paths_post

        """
        pass

    def test_api_course_get(self):
        """Test case for api_course_get

        """
        pass

    def test_api_course_instruction_type_get(self):
        """Test case for api_course_instruction_type_get

        """
        pass

    def test_api_course_instruction_type_options(self):
        """Test case for api_course_instruction_type_options

        """
        pass

    def test_api_course_options(self):
        """Test case for api_course_options

        """
        pass

    def test_api_course_post(self):
        """Test case for api_course_post

        """
        pass

    def test_api_course_transfer_type_get(self):
        """Test case for api_course_transfer_type_get

        """
        pass

    def test_api_course_transfer_type_options(self):
        """Test case for api_course_transfer_type_options

        """
        pass

    def test_api_course_type_get(self):
        """Test case for api_course_type_get

        """
        pass

    def test_api_course_type_options(self):
        """Test case for api_course_type_options

        """
        pass

    def test_api_course_type_post(self):
        """Test case for api_course_type_post

        """
        pass

    def test_api_courses_courses_uuid_delete(self):
        """Test case for api_courses_courses_uuid_delete

        """
        pass

    def test_api_courses_courses_uuid_get(self):
        """Test case for api_courses_courses_uuid_get

        """
        pass

    def test_api_courses_courses_uuid_options(self):
        """Test case for api_courses_courses_uuid_options

        """
        pass

    def test_api_courses_courses_uuid_patch(self):
        """Test case for api_courses_courses_uuid_patch

        """
        pass

    def test_api_courses_courses_uuid_put(self):
        """Test case for api_courses_courses_uuid_put

        """
        pass

    def test_api_courses_get(self):
        """Test case for api_courses_get

        """
        pass

    def test_api_courses_options(self):
        """Test case for api_courses_options

        """
        pass

    def test_api_courses_post(self):
        """Test case for api_courses_post

        """
        pass

    def test_api_create_survey_options(self):
        """Test case for api_create_survey_options

        """
        pass

    def test_api_create_survey_post(self):
        """Test case for api_create_survey_post

        """
        pass

    def test_api_credit_status_get(self):
        """Test case for api_credit_status_get

        """
        pass

    def test_api_credit_status_options(self):
        """Test case for api_credit_status_options

        """
        pass

    def test_api_del_path_attachment_options(self):
        """Test case for api_del_path_attachment_options

        """
        pass

    def test_api_del_path_attachment_post(self):
        """Test case for api_del_path_attachment_post

        """
        pass

    def test_api_department_department_uuid_get(self):
        """Test case for api_department_department_uuid_get

        """
        pass

    def test_api_department_department_uuid_options(self):
        """Test case for api_department_department_uuid_options

        """
        pass

    def test_api_department_get(self):
        """Test case for api_department_get

        """
        pass

    def test_api_department_options(self):
        """Test case for api_department_options

        """
        pass

    def test_api_department_post(self):
        """Test case for api_department_post

        """
        pass

    def test_api_event_attachment_attachment_uuid_delete(self):
        """Test case for api_event_attachment_attachment_uuid_delete

        """
        pass

    def test_api_event_attachment_attachment_uuid_get(self):
        """Test case for api_event_attachment_attachment_uuid_get

        """
        pass

    def test_api_event_attachment_attachment_uuid_options(self):
        """Test case for api_event_attachment_attachment_uuid_options

        """
        pass

    def test_api_event_attachment_attachment_uuid_patch(self):
        """Test case for api_event_attachment_attachment_uuid_patch

        """
        pass

    def test_api_event_banner_event_uuid_delete(self):
        """Test case for api_event_banner_event_uuid_delete

        """
        pass

    def test_api_event_banner_event_uuid_options(self):
        """Test case for api_event_banner_event_uuid_options

        """
        pass

    def test_api_event_detail_srm_get(self):
        """Test case for api_event_detail_srm_get

        """
        pass

    def test_api_event_detail_srm_options(self):
        """Test case for api_event_detail_srm_options

        """
        pass

    def test_api_event_event_uuid_delete(self):
        """Test case for api_event_event_uuid_delete

        """
        pass

    def test_api_event_event_uuid_get(self):
        """Test case for api_event_event_uuid_get

        """
        pass

    def test_api_event_event_uuid_options(self):
        """Test case for api_event_event_uuid_options

        """
        pass

    def test_api_event_event_uuid_patch(self):
        """Test case for api_event_event_uuid_patch

        """
        pass

    def test_api_event_event_uuid_put(self):
        """Test case for api_event_event_uuid_put

        """
        pass

    def test_api_event_get(self):
        """Test case for api_event_get

        """
        pass

    def test_api_event_options(self):
        """Test case for api_event_options

        """
        pass

    def test_api_event_post(self):
        """Test case for api_event_post

        """
        pass

    def test_api_filter_paths_options(self):
        """Test case for api_filter_paths_options

        """
        pass

    def test_api_filter_paths_post(self):
        """Test case for api_filter_paths_post

        """
        pass

    def test_api_gened_get(self):
        """Test case for api_gened_get

        """
        pass

    def test_api_gened_options(self):
        """Test case for api_gened_options

        """
        pass

    def test_api_gened_post(self):
        """Test case for api_gened_post

        """
        pass

    def test_api_gened_put(self):
        """Test case for api_gened_put

        """
        pass

    def test_api_gened_uuid_get(self):
        """Test case for api_gened_uuid_get

        """
        pass

    def test_api_gened_uuid_options(self):
        """Test case for api_gened_uuid_options

        """
        pass

    def test_api_gened_uuid_patch(self):
        """Test case for api_gened_uuid_patch

        """
        pass

    def test_api_gened_uuid_put(self):
        """Test case for api_gened_uuid_put

        """
        pass

    def test_api_gepath_search_get(self):
        """Test case for api_gepath_search_get

        """
        pass

    def test_api_gepath_search_options(self):
        """Test case for api_gepath_search_options

        """
        pass

    def test_api_get_institute_metrics_institution_uuid_get(self):
        """Test case for api_get_institute_metrics_institution_uuid_get

        """
        pass

    def test_api_get_institute_metrics_institution_uuid_options(self):
        """Test case for api_get_institute_metrics_institution_uuid_options

        """
        pass

    def test_api_get_paths_get(self):
        """Test case for api_get_paths_get

        """
        pass

    def test_api_get_paths_options(self):
        """Test case for api_get_paths_options

        """
        pass

    def test_api_get_student_success_timeline_get(self):
        """Test case for api_get_student_success_timeline_get

        """
        pass

    def test_api_get_student_success_timeline_options(self):
        """Test case for api_get_student_success_timeline_options

        """
        pass

    def test_api_gps_acheivement_options_acheivement_options_get(self):
        """Test case for api_gps_acheivement_options_acheivement_options_get

        """
        pass

    def test_api_gps_acheivement_options_acheivement_options_options(self):
        """Test case for api_gps_acheivement_options_acheivement_options_options

        """
        pass

    def test_api_gps_acheivement_options_get(self):
        """Test case for api_gps_acheivement_options_get

        """
        pass

    def test_api_gps_acheivement_options_options(self):
        """Test case for api_gps_acheivement_options_options

        """
        pass

    def test_api_gps_business_partner_cluster_get(self):
        """Test case for api_gps_business_partner_cluster_get

        """
        pass

    def test_api_gps_business_partner_cluster_options(self):
        """Test case for api_gps_business_partner_cluster_options

        """
        pass

    def test_api_gps_business_partner_company_profile_company_profile_uuid_get(self):
        """Test case for api_gps_business_partner_company_profile_company_profile_uuid_get

        """
        pass

    def test_api_gps_business_partner_company_profile_company_profile_uuid_options(self):
        """Test case for api_gps_business_partner_company_profile_company_profile_uuid_options

        """
        pass

    def test_api_gps_business_partner_company_profile_get(self):
        """Test case for api_gps_business_partner_company_profile_get

        """
        pass

    def test_api_gps_business_partner_company_profile_options(self):
        """Test case for api_gps_business_partner_company_profile_options

        """
        pass

    def test_api_gps_business_partner_event_event_uuid_get(self):
        """Test case for api_gps_business_partner_event_event_uuid_get

        """
        pass

    def test_api_gps_business_partner_event_event_uuid_options(self):
        """Test case for api_gps_business_partner_event_event_uuid_options

        """
        pass

    def test_api_gps_business_partner_event_get(self):
        """Test case for api_gps_business_partner_event_get

        """
        pass

    def test_api_gps_business_partner_event_options(self):
        """Test case for api_gps_business_partner_event_options

        """
        pass

    def test_api_gps_business_partner_jobs_get(self):
        """Test case for api_gps_business_partner_jobs_get

        """
        pass

    def test_api_gps_business_partner_jobs_jobs_uuid_get(self):
        """Test case for api_gps_business_partner_jobs_jobs_uuid_get

        """
        pass

    def test_api_gps_business_partner_jobs_jobs_uuid_options(self):
        """Test case for api_gps_business_partner_jobs_jobs_uuid_options

        """
        pass

    def test_api_gps_business_partner_jobs_options(self):
        """Test case for api_gps_business_partner_jobs_options

        """
        pass

    def test_api_gps_business_partner_occupation_get(self):
        """Test case for api_gps_business_partner_occupation_get

        """
        pass

    def test_api_gps_business_partner_occupation_occupation_uuid_get(self):
        """Test case for api_gps_business_partner_occupation_occupation_uuid_get

        """
        pass

    def test_api_gps_business_partner_occupation_occupation_uuid_options(self):
        """Test case for api_gps_business_partner_occupation_occupation_uuid_options

        """
        pass

    def test_api_gps_business_partner_occupation_options(self):
        """Test case for api_gps_business_partner_occupation_options

        """
        pass

    def test_api_gps_business_partner_program_get(self):
        """Test case for api_gps_business_partner_program_get

        """
        pass

    def test_api_gps_business_partner_program_options(self):
        """Test case for api_gps_business_partner_program_options

        """
        pass

    def test_api_gps_business_partner_program_program_uuid_get(self):
        """Test case for api_gps_business_partner_program_program_uuid_get

        """
        pass

    def test_api_gps_business_partner_program_program_uuid_options(self):
        """Test case for api_gps_business_partner_program_program_uuid_options

        """
        pass

    def test_api_gps_business_partner_program_related_to_occupation_get(self):
        """Test case for api_gps_business_partner_program_related_to_occupation_get

        """
        pass

    def test_api_gps_business_partner_program_related_to_occupation_options(self):
        """Test case for api_gps_business_partner_program_related_to_occupation_options

        """
        pass

    def test_api_gps_cluster_cluster_uuid_get(self):
        """Test case for api_gps_cluster_cluster_uuid_get

        """
        pass

    def test_api_gps_cluster_cluster_uuid_options(self):
        """Test case for api_gps_cluster_cluster_uuid_options

        """
        pass

    def test_api_gps_cluster_get(self):
        """Test case for api_gps_cluster_get

        """
        pass

    def test_api_gps_cluster_options(self):
        """Test case for api_gps_cluster_options

        """
        pass

    def test_api_gps_course_map_course_map_uuid_get(self):
        """Test case for api_gps_course_map_course_map_uuid_get

        """
        pass

    def test_api_gps_course_map_course_map_uuid_options(self):
        """Test case for api_gps_course_map_course_map_uuid_options

        """
        pass

    def test_api_gps_course_map_get(self):
        """Test case for api_gps_course_map_get

        """
        pass

    def test_api_gps_course_map_options(self):
        """Test case for api_gps_course_map_options

        """
        pass

    def test_api_gps_course_map_post(self):
        """Test case for api_gps_course_map_post

        """
        pass

    def test_api_gps_courses_courses_uuid_get(self):
        """Test case for api_gps_courses_courses_uuid_get

        """
        pass

    def test_api_gps_courses_courses_uuid_options(self):
        """Test case for api_gps_courses_courses_uuid_options

        """
        pass

    def test_api_gps_courses_get(self):
        """Test case for api_gps_courses_get

        """
        pass

    def test_api_gps_courses_options(self):
        """Test case for api_gps_courses_options

        """
        pass

    def test_api_gps_event_detail_get(self):
        """Test case for api_gps_event_detail_get

        """
        pass

    def test_api_gps_event_detail_options(self):
        """Test case for api_gps_event_detail_options

        """
        pass

    def test_api_gps_gened_get(self):
        """Test case for api_gps_gened_get

        """
        pass

    def test_api_gps_gened_options(self):
        """Test case for api_gps_gened_options

        """
        pass

    def test_api_gps_get_programs_for_path_get(self):
        """Test case for api_gps_get_programs_for_path_get

        """
        pass

    def test_api_gps_get_programs_for_path_options(self):
        """Test case for api_gps_get_programs_for_path_options

        """
        pass

    def test_api_gps_increase_path_count_get(self):
        """Test case for api_gps_increase_path_count_get

        """
        pass

    def test_api_gps_increase_path_count_options(self):
        """Test case for api_gps_increase_path_count_options

        """
        pass

    def test_api_gps_increase_path_count_post(self):
        """Test case for api_gps_increase_path_count_post

        """
        pass

    def test_api_gps_industry_places_cluster_get(self):
        """Test case for api_gps_industry_places_cluster_get

        """
        pass

    def test_api_gps_industry_places_cluster_options(self):
        """Test case for api_gps_industry_places_cluster_options

        """
        pass

    def test_api_gps_industry_places_program_get(self):
        """Test case for api_gps_industry_places_program_get

        """
        pass

    def test_api_gps_industry_places_program_options(self):
        """Test case for api_gps_industry_places_program_options

        """
        pass

    def test_api_gps_industry_places_urls_get(self):
        """Test case for api_gps_industry_places_urls_get

        """
        pass

    def test_api_gps_industry_places_urls_options(self):
        """Test case for api_gps_industry_places_urls_options

        """
        pass

    def test_api_gps_industry_sectors_get(self):
        """Test case for api_gps_industry_sectors_get

        """
        pass

    def test_api_gps_industry_sectors_options(self):
        """Test case for api_gps_industry_sectors_options

        """
        pass

    def test_api_gps_industry_sectors_uuid_get(self):
        """Test case for api_gps_industry_sectors_uuid_get

        """
        pass

    def test_api_gps_industry_sectors_uuid_options(self):
        """Test case for api_gps_industry_sectors_uuid_options

        """
        pass

    def test_api_gps_industry_subsectors_get(self):
        """Test case for api_gps_industry_subsectors_get

        """
        pass

    def test_api_gps_industry_subsectors_options(self):
        """Test case for api_gps_industry_subsectors_options

        """
        pass

    def test_api_gps_industry_subsectors_uuid_get(self):
        """Test case for api_gps_industry_subsectors_uuid_get

        """
        pass

    def test_api_gps_industry_subsectors_uuid_options(self):
        """Test case for api_gps_industry_subsectors_uuid_options

        """
        pass

    def test_api_gps_institute_get(self):
        """Test case for api_gps_institute_get

        """
        pass

    def test_api_gps_institute_institution_id_get(self):
        """Test case for api_gps_institute_institution_id_get

        """
        pass

    def test_api_gps_institute_institution_id_options(self):
        """Test case for api_gps_institute_institution_id_options

        """
        pass

    def test_api_gps_institute_options(self):
        """Test case for api_gps_institute_options

        """
        pass

    def test_api_gps_institute_type_get(self):
        """Test case for api_gps_institute_type_get

        """
        pass

    def test_api_gps_institute_type_options(self):
        """Test case for api_gps_institute_type_options

        """
        pass

    def test_api_gps_milestone_get(self):
        """Test case for api_gps_milestone_get

        """
        pass

    def test_api_gps_milestone_milestone_uuid_get(self):
        """Test case for api_gps_milestone_milestone_uuid_get

        """
        pass

    def test_api_gps_milestone_milestone_uuid_options(self):
        """Test case for api_gps_milestone_milestone_uuid_options

        """
        pass

    def test_api_gps_milestone_options(self):
        """Test case for api_gps_milestone_options

        """
        pass

    def test_api_gps_milestone_type_get(self):
        """Test case for api_gps_milestone_type_get

        """
        pass

    def test_api_gps_milestone_type_milestone_type_uuid_get(self):
        """Test case for api_gps_milestone_type_milestone_type_uuid_get

        """
        pass

    def test_api_gps_milestone_type_milestone_type_uuid_options(self):
        """Test case for api_gps_milestone_type_milestone_type_uuid_options

        """
        pass

    def test_api_gps_milestone_type_options(self):
        """Test case for api_gps_milestone_type_options

        """
        pass

    def test_api_gps_occupation_detail_get(self):
        """Test case for api_gps_occupation_detail_get

        """
        pass

    def test_api_gps_occupation_detail_options(self):
        """Test case for api_gps_occupation_detail_options

        """
        pass

    def test_api_gps_occupation_detail_post(self):
        """Test case for api_gps_occupation_detail_post

        """
        pass

    def test_api_gps_occupation_get(self):
        """Test case for api_gps_occupation_get

        """
        pass

    def test_api_gps_occupation_occupation_uuid_get(self):
        """Test case for api_gps_occupation_occupation_uuid_get

        """
        pass

    def test_api_gps_occupation_occupation_uuid_options(self):
        """Test case for api_gps_occupation_occupation_uuid_options

        """
        pass

    def test_api_gps_occupation_occupation_uuid_post(self):
        """Test case for api_gps_occupation_occupation_uuid_post

        """
        pass

    def test_api_gps_occupation_options(self):
        """Test case for api_gps_occupation_options

        """
        pass

    def test_api_gps_occupation_post(self):
        """Test case for api_gps_occupation_post

        """
        pass

    def test_api_gps_occupation_roles_get(self):
        """Test case for api_gps_occupation_roles_get

        """
        pass

    def test_api_gps_occupation_roles_onnet_id_get(self):
        """Test case for api_gps_occupation_roles_onnet_id_get

        """
        pass

    def test_api_gps_occupation_roles_onnet_id_options(self):
        """Test case for api_gps_occupation_roles_onnet_id_options

        """
        pass

    def test_api_gps_occupation_roles_options(self):
        """Test case for api_gps_occupation_roles_options

        """
        pass

    def test_api_gps_onboarding_path_get(self):
        """Test case for api_gps_onboarding_path_get

        """
        pass

    def test_api_gps_onboarding_path_onboarding_path_uuid_get(self):
        """Test case for api_gps_onboarding_path_onboarding_path_uuid_get

        """
        pass

    def test_api_gps_onboarding_path_onboarding_path_uuid_options(self):
        """Test case for api_gps_onboarding_path_onboarding_path_uuid_options

        """
        pass

    def test_api_gps_onboarding_path_options(self):
        """Test case for api_gps_onboarding_path_options

        """
        pass

    def test_api_gps_onboarding_type_get(self):
        """Test case for api_gps_onboarding_type_get

        """
        pass

    def test_api_gps_onboarding_type_onboarding_type_uuid_get(self):
        """Test case for api_gps_onboarding_type_onboarding_type_uuid_get

        """
        pass

    def test_api_gps_onboarding_type_onboarding_type_uuid_options(self):
        """Test case for api_gps_onboarding_type_onboarding_type_uuid_options

        """
        pass

    def test_api_gps_onboarding_type_options(self):
        """Test case for api_gps_onboarding_type_options

        """
        pass

    def test_api_gps_outreach_v1_event_detail_get(self):
        """Test case for api_gps_outreach_v1_event_detail_get

        """
        pass

    def test_api_gps_outreach_v1_event_detail_options(self):
        """Test case for api_gps_outreach_v1_event_detail_options

        """
        pass

    def test_api_gps_outreach_v1_student_signedup_event_detail_get(self):
        """Test case for api_gps_outreach_v1_student_signedup_event_detail_get

        """
        pass

    def test_api_gps_outreach_v1_student_signedup_event_detail_options(self):
        """Test case for api_gps_outreach_v1_student_signedup_event_detail_options

        """
        pass

    def test_api_gps_path_type_name_get(self):
        """Test case for api_gps_path_type_name_get

        """
        pass

    def test_api_gps_path_type_name_options(self):
        """Test case for api_gps_path_type_name_options

        """
        pass

    def test_api_gps_path_type_name_path_type_name_uuid_get(self):
        """Test case for api_gps_path_type_name_path_type_name_uuid_get

        """
        pass

    def test_api_gps_path_type_name_path_type_name_uuid_options(self):
        """Test case for api_gps_path_type_name_path_type_name_uuid_options

        """
        pass

    def test_api_gps_pathway_planner_get(self):
        """Test case for api_gps_pathway_planner_get

        """
        pass

    def test_api_gps_pathway_planner_options(self):
        """Test case for api_gps_pathway_planner_options

        """
        pass

    def test_api_gps_pathway_planner_post(self):
        """Test case for api_gps_pathway_planner_post

        """
        pass

    def test_api_gps_pathway_planner_put(self):
        """Test case for api_gps_pathway_planner_put

        """
        pass

    def test_api_gps_program_duration_get(self):
        """Test case for api_gps_program_duration_get

        """
        pass

    def test_api_gps_program_duration_options(self):
        """Test case for api_gps_program_duration_options

        """
        pass

    def test_api_gps_program_duration_program_duration_uuid_get(self):
        """Test case for api_gps_program_duration_program_duration_uuid_get

        """
        pass

    def test_api_gps_program_duration_program_duration_uuid_options(self):
        """Test case for api_gps_program_duration_program_duration_uuid_options

        """
        pass

    def test_api_gps_program_get(self):
        """Test case for api_gps_program_get

        """
        pass

    def test_api_gps_program_options(self):
        """Test case for api_gps_program_options

        """
        pass

    def test_api_gps_program_program_uuid_get(self):
        """Test case for api_gps_program_program_uuid_get

        """
        pass

    def test_api_gps_program_program_uuid_options(self):
        """Test case for api_gps_program_program_uuid_options

        """
        pass

    def test_api_gps_publish_get(self):
        """Test case for api_gps_publish_get

        """
        pass

    def test_api_gps_publish_options(self):
        """Test case for api_gps_publish_options

        """
        pass

    def test_api_gps_publish_path_uuid_get(self):
        """Test case for api_gps_publish_path_uuid_get

        """
        pass

    def test_api_gps_publish_path_uuid_options(self):
        """Test case for api_gps_publish_path_uuid_options

        """
        pass

    def test_api_gps_publish_v1_get(self):
        """Test case for api_gps_publish_v1_get

        """
        pass

    def test_api_gps_publish_v1_options(self):
        """Test case for api_gps_publish_v1_options

        """
        pass

    def test_api_gps_publish_v1_path_uuid_get(self):
        """Test case for api_gps_publish_v1_path_uuid_get

        """
        pass

    def test_api_gps_publish_v1_path_uuid_options(self):
        """Test case for api_gps_publish_v1_path_uuid_options

        """
        pass

    def test_api_gps_skills_get(self):
        """Test case for api_gps_skills_get

        """
        pass

    def test_api_gps_skills_options(self):
        """Test case for api_gps_skills_options

        """
        pass

    def test_api_gps_strong_workforce_get_student_details_get(self):
        """Test case for api_gps_strong_workforce_get_student_details_get

        """
        pass

    def test_api_gps_strong_workforce_get_student_details_options(self):
        """Test case for api_gps_strong_workforce_get_student_details_options

        """
        pass

    def test_api_gps_strong_workforce_submit_survey_options(self):
        """Test case for api_gps_strong_workforce_submit_survey_options

        """
        pass

    def test_api_gps_strong_workforce_submit_survey_post(self):
        """Test case for api_gps_strong_workforce_submit_survey_post

        """
        pass

    def test_api_gps_student_survey_get(self):
        """Test case for api_gps_student_survey_get

        """
        pass

    def test_api_gps_student_survey_options(self):
        """Test case for api_gps_student_survey_options

        """
        pass

    def test_api_gps_student_survey_post(self):
        """Test case for api_gps_student_survey_post

        """
        pass

    def test_api_gps_submit_survey_options(self):
        """Test case for api_gps_submit_survey_options

        """
        pass

    def test_api_gps_submit_survey_post(self):
        """Test case for api_gps_submit_survey_post

        """
        pass

    def test_api_gps_type_of_student_get(self):
        """Test case for api_gps_type_of_student_get

        """
        pass

    def test_api_gps_type_of_student_options(self):
        """Test case for api_gps_type_of_student_options

        """
        pass

    def test_api_industry_places_cluster_get(self):
        """Test case for api_industry_places_cluster_get

        """
        pass

    def test_api_industry_places_cluster_options(self):
        """Test case for api_industry_places_cluster_options

        """
        pass

    def test_api_industry_places_program_get(self):
        """Test case for api_industry_places_program_get

        """
        pass

    def test_api_industry_places_program_industry_places_program_uuid_delete(self):
        """Test case for api_industry_places_program_industry_places_program_uuid_delete

        """
        pass

    def test_api_industry_places_program_industry_places_program_uuid_get(self):
        """Test case for api_industry_places_program_industry_places_program_uuid_get

        """
        pass

    def test_api_industry_places_program_industry_places_program_uuid_options(self):
        """Test case for api_industry_places_program_industry_places_program_uuid_options

        """
        pass

    def test_api_industry_places_program_industry_places_program_uuid_patch(self):
        """Test case for api_industry_places_program_industry_places_program_uuid_patch

        """
        pass

    def test_api_industry_places_program_industry_places_program_uuid_put(self):
        """Test case for api_industry_places_program_industry_places_program_uuid_put

        """
        pass

    def test_api_industry_places_program_options(self):
        """Test case for api_industry_places_program_options

        """
        pass

    def test_api_industry_places_program_post(self):
        """Test case for api_industry_places_program_post

        """
        pass

    def test_api_industry_sectors_get(self):
        """Test case for api_industry_sectors_get

        """
        pass

    def test_api_industry_sectors_options(self):
        """Test case for api_industry_sectors_options

        """
        pass

    def test_api_industry_sectors_uuid_get(self):
        """Test case for api_industry_sectors_uuid_get

        """
        pass

    def test_api_industry_sectors_uuid_options(self):
        """Test case for api_industry_sectors_uuid_options

        """
        pass

    def test_api_industry_subsectors_get(self):
        """Test case for api_industry_subsectors_get

        """
        pass

    def test_api_industry_subsectors_options(self):
        """Test case for api_industry_subsectors_options

        """
        pass

    def test_api_industry_subsectors_uuid_get(self):
        """Test case for api_industry_subsectors_uuid_get

        """
        pass

    def test_api_industry_subsectors_uuid_options(self):
        """Test case for api_industry_subsectors_uuid_options

        """
        pass

    def test_api_institute_get(self):
        """Test case for api_institute_get

        """
        pass

    def test_api_institute_institute_id_delete(self):
        """Test case for api_institute_institute_id_delete

        """
        pass

    def test_api_institute_institute_id_get(self):
        """Test case for api_institute_institute_id_get

        """
        pass

    def test_api_institute_institute_id_options(self):
        """Test case for api_institute_institute_id_options

        """
        pass

    def test_api_institute_institute_id_patch(self):
        """Test case for api_institute_institute_id_patch

        """
        pass

    def test_api_institute_institute_id_put(self):
        """Test case for api_institute_institute_id_put

        """
        pass

    def test_api_institute_options(self):
        """Test case for api_institute_options

        """
        pass

    def test_api_institute_post(self):
        """Test case for api_institute_post

        """
        pass

    def test_api_institute_super_type_get(self):
        """Test case for api_institute_super_type_get

        """
        pass

    def test_api_institute_super_type_options(self):
        """Test case for api_institute_super_type_options

        """
        pass

    def test_api_institute_timeline_get(self):
        """Test case for api_institute_timeline_get

        """
        pass

    def test_api_institute_timeline_options(self):
        """Test case for api_institute_timeline_options

        """
        pass

    def test_api_institute_type_get(self):
        """Test case for api_institute_type_get

        """
        pass

    def test_api_institute_type_options(self):
        """Test case for api_institute_type_options

        """
        pass

    def test_api_institute_type_permission_get(self):
        """Test case for api_institute_type_permission_get

        """
        pass

    def test_api_institute_type_permission_institute_type_permission_uuid_get(self):
        """Test case for api_institute_type_permission_institute_type_permission_uuid_get

        """
        pass

    def test_api_institute_type_permission_institute_type_permission_uuid_options(self):
        """Test case for api_institute_type_permission_institute_type_permission_uuid_options

        """
        pass

    def test_api_institute_type_permission_options(self):
        """Test case for api_institute_type_permission_options

        """
        pass

    def test_api_institute_type_permission_post(self):
        """Test case for api_institute_type_permission_post

        """
        pass

    def test_api_institution_sub_type_get(self):
        """Test case for api_institution_sub_type_get

        """
        pass

    def test_api_institution_sub_type_institution_uuid_get(self):
        """Test case for api_institution_sub_type_institution_uuid_get

        """
        pass

    def test_api_institution_sub_type_institution_uuid_options(self):
        """Test case for api_institution_sub_type_institution_uuid_options

        """
        pass

    def test_api_institution_sub_type_options(self):
        """Test case for api_institution_sub_type_options

        """
        pass

    def test_api_institution_type_get(self):
        """Test case for api_institution_type_get

        """
        pass

    def test_api_institution_type_options(self):
        """Test case for api_institution_type_options

        """
        pass

    def test_api_institution_v1_delete(self):
        """Test case for api_institution_v1_delete

        """
        pass

    def test_api_institution_v1_get(self):
        """Test case for api_institution_v1_get

        """
        pass

    def test_api_institution_v1_institution_uuid_delete(self):
        """Test case for api_institution_v1_institution_uuid_delete

        """
        pass

    def test_api_institution_v1_institution_uuid_get(self):
        """Test case for api_institution_v1_institution_uuid_get

        """
        pass

    def test_api_institution_v1_institution_uuid_options(self):
        """Test case for api_institution_v1_institution_uuid_options

        """
        pass

    def test_api_institution_v1_institution_uuid_patch(self):
        """Test case for api_institution_v1_institution_uuid_patch

        """
        pass

    def test_api_institution_v1_institution_uuid_put(self):
        """Test case for api_institution_v1_institution_uuid_put

        """
        pass

    def test_api_institution_v1_options(self):
        """Test case for api_institution_v1_options

        """
        pass

    def test_api_institution_v1_post(self):
        """Test case for api_institution_v1_post

        """
        pass

    def test_api_institution_v1_put(self):
        """Test case for api_institution_v1_put

        """
        pass

    def test_api_lead_data_lead_map_uuid_options(self):
        """Test case for api_lead_data_lead_map_uuid_options

        """
        pass

    def test_api_lead_data_lead_map_uuid_put(self):
        """Test case for api_lead_data_lead_map_uuid_put

        """
        pass

    def test_api_lead_data_options(self):
        """Test case for api_lead_data_options

        """
        pass

    def test_api_lead_data_post(self):
        """Test case for api_lead_data_post

        """
        pass

    def test_api_lead_map_get(self):
        """Test case for api_lead_map_get

        """
        pass

    def test_api_lead_map_lead_map_uuid_options(self):
        """Test case for api_lead_map_lead_map_uuid_options

        """
        pass

    def test_api_lead_map_lead_map_uuid_put(self):
        """Test case for api_lead_map_lead_map_uuid_put

        """
        pass

    def test_api_lead_map_options(self):
        """Test case for api_lead_map_options

        """
        pass

    def test_api_lead_map_post(self):
        """Test case for api_lead_map_post

        """
        pass

    def test_api_message_leads_options(self):
        """Test case for api_message_leads_options

        """
        pass

    def test_api_message_leads_post(self):
        """Test case for api_message_leads_post

        """
        pass

    def test_api_message_staff_options(self):
        """Test case for api_message_staff_options

        """
        pass

    def test_api_message_staff_post(self):
        """Test case for api_message_staff_post

        """
        pass

    def test_api_milestone_get(self):
        """Test case for api_milestone_get

        """
        pass

    def test_api_milestone_milestone_uuid_get(self):
        """Test case for api_milestone_milestone_uuid_get

        """
        pass

    def test_api_milestone_milestone_uuid_options(self):
        """Test case for api_milestone_milestone_uuid_options

        """
        pass

    def test_api_milestone_milestone_uuid_patch(self):
        """Test case for api_milestone_milestone_uuid_patch

        """
        pass

    def test_api_milestone_milestone_uuid_put(self):
        """Test case for api_milestone_milestone_uuid_put

        """
        pass

    def test_api_milestone_options(self):
        """Test case for api_milestone_options

        """
        pass

    def test_api_milestone_post(self):
        """Test case for api_milestone_post

        """
        pass

    def test_api_milestone_resource_get(self):
        """Test case for api_milestone_resource_get

        """
        pass

    def test_api_milestone_resource_options(self):
        """Test case for api_milestone_resource_options

        """
        pass

    def test_api_milestone_resource_post(self):
        """Test case for api_milestone_resource_post

        """
        pass

    def test_api_milestone_type_get(self):
        """Test case for api_milestone_type_get

        """
        pass

    def test_api_milestone_type_options(self):
        """Test case for api_milestone_type_options

        """
        pass

    def test_api_milestone_type_post(self):
        """Test case for api_milestone_type_post

        """
        pass

    def test_api_module_get(self):
        """Test case for api_module_get

        """
        pass

    def test_api_module_options(self):
        """Test case for api_module_options

        """
        pass

    def test_api_notification_v1_notification_settings_get(self):
        """Test case for api_notification_v1_notification_settings_get

        """
        pass

    def test_api_notification_v1_notification_settings_notification_uuid_options(self):
        """Test case for api_notification_v1_notification_settings_notification_uuid_options

        """
        pass

    def test_api_notification_v1_notification_settings_notification_uuid_patch(self):
        """Test case for api_notification_v1_notification_settings_notification_uuid_patch

        """
        pass

    def test_api_notification_v1_notification_settings_options(self):
        """Test case for api_notification_v1_notification_settings_options

        """
        pass

    def test_api_notification_v1_notifications_get(self):
        """Test case for api_notification_v1_notifications_get

        """
        pass

    def test_api_notification_v1_notifications_options(self):
        """Test case for api_notification_v1_notifications_options

        """
        pass

    def test_api_notification_v1_notifications_user_uuid_options(self):
        """Test case for api_notification_v1_notifications_user_uuid_options

        """
        pass

    def test_api_notification_v1_notifications_user_uuid_patch(self):
        """Test case for api_notification_v1_notifications_user_uuid_patch

        """
        pass

    def test_api_occupation_get(self):
        """Test case for api_occupation_get

        """
        pass

    def test_api_occupation_options(self):
        """Test case for api_occupation_options

        """
        pass

    def test_api_occupation_post(self):
        """Test case for api_occupation_post

        """
        pass

    def test_api_occupation_roles_get(self):
        """Test case for api_occupation_roles_get

        """
        pass

    def test_api_occupation_roles_options(self):
        """Test case for api_occupation_roles_options

        """
        pass

    def test_api_onboarding_path_get(self):
        """Test case for api_onboarding_path_get

        """
        pass

    def test_api_onboarding_path_onboarding_path_uuid_delete(self):
        """Test case for api_onboarding_path_onboarding_path_uuid_delete

        """
        pass

    def test_api_onboarding_path_onboarding_path_uuid_get(self):
        """Test case for api_onboarding_path_onboarding_path_uuid_get

        """
        pass

    def test_api_onboarding_path_onboarding_path_uuid_options(self):
        """Test case for api_onboarding_path_onboarding_path_uuid_options

        """
        pass

    def test_api_onboarding_path_onboarding_path_uuid_patch(self):
        """Test case for api_onboarding_path_onboarding_path_uuid_patch

        """
        pass

    def test_api_onboarding_path_onboarding_path_uuid_put(self):
        """Test case for api_onboarding_path_onboarding_path_uuid_put

        """
        pass

    def test_api_onboarding_path_options(self):
        """Test case for api_onboarding_path_options

        """
        pass

    def test_api_onboarding_path_post(self):
        """Test case for api_onboarding_path_post

        """
        pass

    def test_api_onboarding_type_get(self):
        """Test case for api_onboarding_type_get

        """
        pass

    def test_api_onboarding_type_onboarding_type_uuid_get(self):
        """Test case for api_onboarding_type_onboarding_type_uuid_get

        """
        pass

    def test_api_onboarding_type_onboarding_type_uuid_options(self):
        """Test case for api_onboarding_type_onboarding_type_uuid_options

        """
        pass

    def test_api_onboarding_type_options(self):
        """Test case for api_onboarding_type_options

        """
        pass

    def test_api_outreach_v1_audience_send_message_options(self):
        """Test case for api_outreach_v1_audience_send_message_options

        """
        pass

    def test_api_outreach_v1_audience_send_message_post(self):
        """Test case for api_outreach_v1_audience_send_message_post

        """
        pass

    def test_api_outreach_v1_event_activity_event_uuid_get(self):
        """Test case for api_outreach_v1_event_activity_event_uuid_get

        """
        pass

    def test_api_outreach_v1_event_activity_event_uuid_options(self):
        """Test case for api_outreach_v1_event_activity_event_uuid_options

        """
        pass

    def test_api_outreach_v1_event_attachment_event_uuid_delete(self):
        """Test case for api_outreach_v1_event_attachment_event_uuid_delete

        """
        pass

    def test_api_outreach_v1_event_attachment_event_uuid_options(self):
        """Test case for api_outreach_v1_event_attachment_event_uuid_options

        """
        pass

    def test_api_outreach_v1_event_banner_event_uuid_delete(self):
        """Test case for api_outreach_v1_event_banner_event_uuid_delete

        """
        pass

    def test_api_outreach_v1_event_banner_event_uuid_options(self):
        """Test case for api_outreach_v1_event_banner_event_uuid_options

        """
        pass

    def test_api_outreach_v1_event_event_uuid_delete(self):
        """Test case for api_outreach_v1_event_event_uuid_delete

        """
        pass

    def test_api_outreach_v1_event_event_uuid_get(self):
        """Test case for api_outreach_v1_event_event_uuid_get

        """
        pass

    def test_api_outreach_v1_event_event_uuid_options(self):
        """Test case for api_outreach_v1_event_event_uuid_options

        """
        pass

    def test_api_outreach_v1_event_event_uuid_patch(self):
        """Test case for api_outreach_v1_event_event_uuid_patch

        """
        pass

    def test_api_outreach_v1_event_event_uuid_put(self):
        """Test case for api_outreach_v1_event_event_uuid_put

        """
        pass

    def test_api_outreach_v1_event_get(self):
        """Test case for api_outreach_v1_event_get

        """
        pass

    def test_api_outreach_v1_event_list_options(self):
        """Test case for api_outreach_v1_event_list_options

        """
        pass

    def test_api_outreach_v1_event_options(self):
        """Test case for api_outreach_v1_event_options

        """
        pass

    def test_api_outreach_v1_event_post(self):
        """Test case for api_outreach_v1_event_post

        """
        pass

    def test_api_outreach_v1_event_send_message_options(self):
        """Test case for api_outreach_v1_event_send_message_options

        """
        pass

    def test_api_outreach_v1_event_send_message_post(self):
        """Test case for api_outreach_v1_event_send_message_post

        """
        pass

    def test_api_outreach_v1_event_signup_event_uuid_delete(self):
        """Test case for api_outreach_v1_event_signup_event_uuid_delete

        """
        pass

    def test_api_outreach_v1_event_signup_event_uuid_options(self):
        """Test case for api_outreach_v1_event_signup_event_uuid_options

        """
        pass

    def test_api_outreach_v1_event_signup_options(self):
        """Test case for api_outreach_v1_event_signup_options

        """
        pass

    def test_api_outreach_v1_event_signup_post(self):
        """Test case for api_outreach_v1_event_signup_post

        """
        pass

    def test_api_outreach_v1_event_student_list_event_uuid_get(self):
        """Test case for api_outreach_v1_event_student_list_event_uuid_get

        """
        pass

    def test_api_outreach_v1_event_student_list_event_uuid_options(self):
        """Test case for api_outreach_v1_event_student_list_event_uuid_options

        """
        pass

    def test_api_overview_content_get(self):
        """Test case for api_overview_content_get

        """
        pass

    def test_api_overview_content_options(self):
        """Test case for api_overview_content_options

        """
        pass

    def test_api_overview_content_post(self):
        """Test case for api_overview_content_post

        """
        pass

    def test_api_overview_values_get(self):
        """Test case for api_overview_values_get

        """
        pass

    def test_api_overview_values_options(self):
        """Test case for api_overview_values_options

        """
        pass

    def test_api_overview_values_post(self):
        """Test case for api_overview_values_post

        """
        pass

    def test_api_partner_dashboard_data_get(self):
        """Test case for api_partner_dashboard_data_get

        """
        pass

    def test_api_partner_dashboard_data_options(self):
        """Test case for api_partner_dashboard_data_options

        """
        pass

    def test_api_partner_dashboard_get(self):
        """Test case for api_partner_dashboard_get

        """
        pass

    def test_api_partner_dashboard_options(self):
        """Test case for api_partner_dashboard_options

        """
        pass

    def test_api_partner_get(self):
        """Test case for api_partner_get

        """
        pass

    def test_api_partner_list_get(self):
        """Test case for api_partner_list_get

        """
        pass

    def test_api_partner_list_options(self):
        """Test case for api_partner_list_options

        """
        pass

    def test_api_partner_list_partner_list_delete(self):
        """Test case for api_partner_list_partner_list_delete

        """
        pass

    def test_api_partner_list_partner_list_get(self):
        """Test case for api_partner_list_partner_list_get

        """
        pass

    def test_api_partner_list_partner_list_options(self):
        """Test case for api_partner_list_partner_list_options

        """
        pass

    def test_api_partner_list_partner_list_patch(self):
        """Test case for api_partner_list_partner_list_patch

        """
        pass

    def test_api_partner_list_partner_list_put(self):
        """Test case for api_partner_list_partner_list_put

        """
        pass

    def test_api_partner_list_post(self):
        """Test case for api_partner_list_post

        """
        pass

    def test_api_partner_message_options(self):
        """Test case for api_partner_message_options

        """
        pass

    def test_api_partner_message_post(self):
        """Test case for api_partner_message_post

        """
        pass

    def test_api_partner_options(self):
        """Test case for api_partner_options

        """
        pass

    def test_api_partner_partner_uuid_get(self):
        """Test case for api_partner_partner_uuid_get

        """
        pass

    def test_api_partner_partner_uuid_options(self):
        """Test case for api_partner_partner_uuid_options

        """
        pass

    def test_api_partner_partner_uuid_patch(self):
        """Test case for api_partner_partner_uuid_patch

        """
        pass

    def test_api_partner_partner_uuid_put(self):
        """Test case for api_partner_partner_uuid_put

        """
        pass

    def test_api_partner_post(self):
        """Test case for api_partner_post

        """
        pass

    def test_api_partner_user_get(self):
        """Test case for api_partner_user_get

        """
        pass

    def test_api_partner_user_options(self):
        """Test case for api_partner_user_options

        """
        pass

    def test_api_partner_user_post(self):
        """Test case for api_partner_user_post

        """
        pass

    def test_api_path_type_name_get(self):
        """Test case for api_path_type_name_get

        """
        pass

    def test_api_path_type_name_options(self):
        """Test case for api_path_type_name_options

        """
        pass

    def test_api_path_type_name_post(self):
        """Test case for api_path_type_name_post

        """
        pass

    def test_api_pathway_planner_get(self):
        """Test case for api_pathway_planner_get

        """
        pass

    def test_api_pathway_planner_options(self):
        """Test case for api_pathway_planner_options

        """
        pass

    def test_api_pathway_planner_patch(self):
        """Test case for api_pathway_planner_patch

        """
        pass

    def test_api_pathway_planner_post(self):
        """Test case for api_pathway_planner_post

        """
        pass

    def test_api_pathway_planner_uuid_options(self):
        """Test case for api_pathway_planner_uuid_options

        """
        pass

    def test_api_pathway_planner_uuid_patch(self):
        """Test case for api_pathway_planner_uuid_patch

        """
        pass

    def test_api_program_duration_get(self):
        """Test case for api_program_duration_get

        """
        pass

    def test_api_program_duration_options(self):
        """Test case for api_program_duration_options

        """
        pass

    def test_api_program_duration_post(self):
        """Test case for api_program_duration_post

        """
        pass

    def test_api_program_get(self):
        """Test case for api_program_get

        """
        pass

    def test_api_program_options(self):
        """Test case for api_program_options

        """
        pass

    def test_api_program_post(self):
        """Test case for api_program_post

        """
        pass

    def test_api_program_skills_get(self):
        """Test case for api_program_skills_get

        """
        pass

    def test_api_program_skills_options(self):
        """Test case for api_program_skills_options

        """
        pass

    def test_api_program_skills_post(self):
        """Test case for api_program_skills_post

        """
        pass

    def test_api_program_to_institue_get(self):
        """Test case for api_program_to_institue_get

        """
        pass

    def test_api_program_to_institue_options(self):
        """Test case for api_program_to_institue_options

        """
        pass

    def test_api_programs_enrollment_get(self):
        """Test case for api_programs_enrollment_get

        """
        pass

    def test_api_programs_enrollment_options(self):
        """Test case for api_programs_enrollment_options

        """
        pass

    def test_api_publish_get(self):
        """Test case for api_publish_get

        """
        pass

    def test_api_publish_options(self):
        """Test case for api_publish_options

        """
        pass

    def test_api_publish_post(self):
        """Test case for api_publish_post

        """
        pass

    def test_api_publish_v1_delete(self):
        """Test case for api_publish_v1_delete

        """
        pass

    def test_api_publish_v1_get(self):
        """Test case for api_publish_v1_get

        """
        pass

    def test_api_publish_v1_options(self):
        """Test case for api_publish_v1_options

        """
        pass

    def test_api_publish_v1_path_uuid_delete(self):
        """Test case for api_publish_v1_path_uuid_delete

        """
        pass

    def test_api_publish_v1_path_uuid_get(self):
        """Test case for api_publish_v1_path_uuid_get

        """
        pass

    def test_api_publish_v1_path_uuid_options(self):
        """Test case for api_publish_v1_path_uuid_options

        """
        pass

    def test_api_publish_v1_path_uuid_patch(self):
        """Test case for api_publish_v1_path_uuid_patch

        """
        pass

    def test_api_publish_v1_path_uuid_put(self):
        """Test case for api_publish_v1_path_uuid_put

        """
        pass

    def test_api_publish_v1_post(self):
        """Test case for api_publish_v1_post

        """
        pass

    def test_api_publish_v1_put(self):
        """Test case for api_publish_v1_put

        """
        pass

    def test_api_refresh_token_options(self):
        """Test case for api_refresh_token_options

        """
        pass

    def test_api_refresh_token_post(self):
        """Test case for api_refresh_token_post

        """
        pass

    def test_api_skills_get(self):
        """Test case for api_skills_get

        """
        pass

    def test_api_skills_options(self):
        """Test case for api_skills_options

        """
        pass

    def test_api_srm_details_student_get(self):
        """Test case for api_srm_details_student_get

        """
        pass

    def test_api_srm_details_student_options(self):
        """Test case for api_srm_details_student_options

        """
        pass

    def test_api_staff_map_get(self):
        """Test case for api_staff_map_get

        """
        pass

    def test_api_staff_map_options(self):
        """Test case for api_staff_map_options

        """
        pass

    def test_api_staff_map_post(self):
        """Test case for api_staff_map_post

        """
        pass

    def test_api_staff_map_staff_uuid_delete(self):
        """Test case for api_staff_map_staff_uuid_delete

        """
        pass

    def test_api_staff_map_staff_uuid_options(self):
        """Test case for api_staff_map_staff_uuid_options

        """
        pass

    def test_api_status_options(self):
        """Test case for api_status_options

        """
        pass

    def test_api_status_patch(self):
        """Test case for api_status_patch

        """
        pass

    def test_api_strong_workforce_create_survey_options(self):
        """Test case for api_strong_workforce_create_survey_options

        """
        pass

    def test_api_strong_workforce_create_survey_post(self):
        """Test case for api_strong_workforce_create_survey_post

        """
        pass

    def test_api_strong_workforce_institution_terms_get(self):
        """Test case for api_strong_workforce_institution_terms_get

        """
        pass

    def test_api_strong_workforce_institution_terms_options(self):
        """Test case for api_strong_workforce_institution_terms_options

        """
        pass

    def test_api_strong_workforce_list_of_programs_get(self):
        """Test case for api_strong_workforce_list_of_programs_get

        """
        pass

    def test_api_strong_workforce_list_of_programs_options(self):
        """Test case for api_strong_workforce_list_of_programs_options

        """
        pass

    def test_api_strong_workforce_student_data_get(self):
        """Test case for api_strong_workforce_student_data_get

        """
        pass

    def test_api_strong_workforce_student_data_options(self):
        """Test case for api_strong_workforce_student_data_options

        """
        pass

    def test_api_strong_workforce_student_data_post(self):
        """Test case for api_strong_workforce_student_data_post

        """
        pass

    def test_api_strong_workforce_survey_details_get(self):
        """Test case for api_strong_workforce_survey_details_get

        """
        pass

    def test_api_strong_workforce_survey_details_options(self):
        """Test case for api_strong_workforce_survey_details_options

        """
        pass

    def test_api_strongworkforce_student_data_get(self):
        """Test case for api_strongworkforce_student_data_get

        """
        pass

    def test_api_strongworkforce_student_data_options(self):
        """Test case for api_strongworkforce_student_data_options

        """
        pass

    def test_api_strongworkforce_student_data_post(self):
        """Test case for api_strongworkforce_student_data_post

        """
        pass

    def test_api_student_survey_delete(self):
        """Test case for api_student_survey_delete

        """
        pass

    def test_api_student_survey_get(self):
        """Test case for api_student_survey_get

        """
        pass

    def test_api_student_survey_options(self):
        """Test case for api_student_survey_options

        """
        pass

    def test_api_student_survey_post(self):
        """Test case for api_student_survey_post

        """
        pass

    def test_api_student_survey_uuid_delete(self):
        """Test case for api_student_survey_uuid_delete

        """
        pass

    def test_api_student_survey_uuid_options(self):
        """Test case for api_student_survey_uuid_options

        """
        pass

    def test_api_subscribe_delete(self):
        """Test case for api_subscribe_delete

        """
        pass

    def test_api_subscribe_get(self):
        """Test case for api_subscribe_get

        """
        pass

    def test_api_subscribe_options(self):
        """Test case for api_subscribe_options

        """
        pass

    def test_api_subscribe_post(self):
        """Test case for api_subscribe_post

        """
        pass

    def test_api_subscribe_subscribe_uuid_delete(self):
        """Test case for api_subscribe_subscribe_uuid_delete

        """
        pass

    def test_api_subscribe_subscribe_uuid_get(self):
        """Test case for api_subscribe_subscribe_uuid_get

        """
        pass

    def test_api_subscribe_subscribe_uuid_options(self):
        """Test case for api_subscribe_subscribe_uuid_options

        """
        pass

    def test_api_super_user_institute_get(self):
        """Test case for api_super_user_institute_get

        """
        pass

    def test_api_super_user_institute_institution_id_delete(self):
        """Test case for api_super_user_institute_institution_id_delete

        """
        pass

    def test_api_super_user_institute_institution_id_get(self):
        """Test case for api_super_user_institute_institution_id_get

        """
        pass

    def test_api_super_user_institute_institution_id_options(self):
        """Test case for api_super_user_institute_institution_id_options

        """
        pass

    def test_api_super_user_institute_institution_id_patch(self):
        """Test case for api_super_user_institute_institution_id_patch

        """
        pass

    def test_api_super_user_institute_institution_id_put(self):
        """Test case for api_super_user_institute_institution_id_put

        """
        pass

    def test_api_super_user_institute_options(self):
        """Test case for api_super_user_institute_options

        """
        pass

    def test_api_super_user_institute_post(self):
        """Test case for api_super_user_institute_post

        """
        pass

    def test_api_super_user_institution_list_get(self):
        """Test case for api_super_user_institution_list_get

        """
        pass

    def test_api_super_user_institution_list_options(self):
        """Test case for api_super_user_institution_list_options

        """
        pass

    def test_api_super_user_refresh_token_options(self):
        """Test case for api_super_user_refresh_token_options

        """
        pass

    def test_api_super_user_refresh_token_post(self):
        """Test case for api_super_user_refresh_token_post

        """
        pass

    def test_api_super_user_token_options(self):
        """Test case for api_super_user_token_options

        """
        pass

    def test_api_super_user_token_post(self):
        """Test case for api_super_user_token_post

        """
        pass

    def test_api_task_attachment_task_attachment_uuid_options(self):
        """Test case for api_task_attachment_task_attachment_uuid_options

        """
        pass

    def test_api_task_attachment_task_attachment_uuid_patch(self):
        """Test case for api_task_attachment_task_attachment_uuid_patch

        """
        pass

    def test_api_token_options(self):
        """Test case for api_token_options

        """
        pass

    def test_api_token_post(self):
        """Test case for api_token_post

        """
        pass

    def test_api_user_confirm_forgot_password_options(self):
        """Test case for api_user_confirm_forgot_password_options

        """
        pass

    def test_api_user_confirm_forgot_password_post(self):
        """Test case for api_user_confirm_forgot_password_post

        """
        pass

    def test_api_user_forgot_password_options(self):
        """Test case for api_user_forgot_password_options

        """
        pass

    def test_api_user_forgot_password_post(self):
        """Test case for api_user_forgot_password_post

        """
        pass

    def test_api_user_forgot_password_put(self):
        """Test case for api_user_forgot_password_put

        """
        pass

    def test_api_user_get(self):
        """Test case for api_user_get

        """
        pass

    def test_api_user_options(self):
        """Test case for api_user_options

        """
        pass

    def test_api_user_picture_user_uuid_options(self):
        """Test case for api_user_picture_user_uuid_options

        """
        pass

    def test_api_user_picture_user_uuid_patch(self):
        """Test case for api_user_picture_user_uuid_patch

        """
        pass

    def test_api_user_post(self):
        """Test case for api_user_post

        """
        pass

    def test_api_user_profile_options(self):
        """Test case for api_user_profile_options

        """
        pass

    def test_api_user_profile_post(self):
        """Test case for api_user_profile_post

        """
        pass

    def test_api_user_profile_user_uuid_options(self):
        """Test case for api_user_profile_user_uuid_options

        """
        pass

    def test_api_user_profile_user_uuid_put(self):
        """Test case for api_user_profile_user_uuid_put

        """
        pass

    def test_api_user_resend_temp_password_options(self):
        """Test case for api_user_resend_temp_password_options

        """
        pass

    def test_api_user_resend_temp_password_post(self):
        """Test case for api_user_resend_temp_password_post

        """
        pass

    def test_api_user_reset_password_options(self):
        """Test case for api_user_reset_password_options

        """
        pass

    def test_api_user_reset_password_post(self):
        """Test case for api_user_reset_password_post

        """
        pass

    def test_api_user_type_get(self):
        """Test case for api_user_type_get

        """
        pass

    def test_api_user_type_options(self):
        """Test case for api_user_type_options

        """
        pass

    def test_api_user_type_post(self):
        """Test case for api_user_type_post

        """
        pass

    def test_api_user_type_premission_get(self):
        """Test case for api_user_type_premission_get

        """
        pass

    def test_api_user_type_premission_options(self):
        """Test case for api_user_type_premission_options

        """
        pass

    def test_api_user_type_premission_post(self):
        """Test case for api_user_type_premission_post

        """
        pass

    def test_api_user_type_premission_user_type_get(self):
        """Test case for api_user_type_premission_user_type_get

        """
        pass

    def test_api_user_type_premission_user_type_options(self):
        """Test case for api_user_type_premission_user_type_options

        """
        pass

    def test_api_user_type_premission_user_type_patch(self):
        """Test case for api_user_type_premission_user_type_patch

        """
        pass

    def test_api_user_type_premission_user_type_put(self):
        """Test case for api_user_type_premission_user_type_put

        """
        pass

    def test_api_user_type_user_type_get(self):
        """Test case for api_user_type_user_type_get

        """
        pass

    def test_api_user_type_user_type_options(self):
        """Test case for api_user_type_user_type_options

        """
        pass

    def test_api_user_type_user_type_patch(self):
        """Test case for api_user_type_user_type_patch

        """
        pass

    def test_api_user_type_user_type_put(self):
        """Test case for api_user_type_user_type_put

        """
        pass

    def test_api_user_user_uuid_delete(self):
        """Test case for api_user_user_uuid_delete

        """
        pass

    def test_api_user_user_uuid_get(self):
        """Test case for api_user_user_uuid_get

        """
        pass

    def test_api_user_user_uuid_options(self):
        """Test case for api_user_user_uuid_options

        """
        pass

    def test_api_user_user_uuid_patch(self):
        """Test case for api_user_user_uuid_patch

        """
        pass

    def test_api_user_user_uuid_put(self):
        """Test case for api_user_user_uuid_put

        """
        pass

    def test_api_v1_super_user_add_institute_user_options(self):
        """Test case for api_v1_super_user_add_institute_user_options

        """
        pass

    def test_api_v1_super_user_add_institute_user_post(self):
        """Test case for api_v1_super_user_add_institute_user_post

        """
        pass

    def test_api_v1_super_user_check_institute_user_options(self):
        """Test case for api_v1_super_user_check_institute_user_options

        """
        pass

    def test_api_v1_super_user_check_institute_user_post(self):
        """Test case for api_v1_super_user_check_institute_user_post

        """
        pass

    def test_api_v1_super_user_delete_institute_user_user_id_delete(self):
        """Test case for api_v1_super_user_delete_institute_user_user_id_delete

        """
        pass

    def test_api_v1_super_user_delete_institute_user_user_id_options(self):
        """Test case for api_v1_super_user_delete_institute_user_user_id_options

        """
        pass

    def test_api_v1_super_user_institute_get(self):
        """Test case for api_v1_super_user_institute_get

        """
        pass

    def test_api_v1_super_user_institute_institution_id_delete(self):
        """Test case for api_v1_super_user_institute_institution_id_delete

        """
        pass

    def test_api_v1_super_user_institute_institution_id_get(self):
        """Test case for api_v1_super_user_institute_institution_id_get

        """
        pass

    def test_api_v1_super_user_institute_institution_id_options(self):
        """Test case for api_v1_super_user_institute_institution_id_options

        """
        pass

    def test_api_v1_super_user_institute_institution_id_patch(self):
        """Test case for api_v1_super_user_institute_institution_id_patch

        """
        pass

    def test_api_v1_super_user_institute_institution_id_put(self):
        """Test case for api_v1_super_user_institute_institution_id_put

        """
        pass

    def test_api_v1_super_user_institute_options(self):
        """Test case for api_v1_super_user_institute_options

        """
        pass

    def test_api_v1_super_user_institute_post(self):
        """Test case for api_v1_super_user_institute_post

        """
        pass

    def test_api_v1_super_user_institute_users_institution_id_get(self):
        """Test case for api_v1_super_user_institute_users_institution_id_get

        """
        pass

    def test_api_v1_super_user_institute_users_institution_id_options(self):
        """Test case for api_v1_super_user_institute_users_institution_id_options

        """
        pass

    def test_api_v1_super_user_institutions_timeline_get(self):
        """Test case for api_v1_super_user_institutions_timeline_get

        """
        pass

    def test_api_v1_super_user_institutions_timeline_options(self):
        """Test case for api_v1_super_user_institutions_timeline_options

        """
        pass

    def test_api_v1_super_user_remove_child_institution_options(self):
        """Test case for api_v1_super_user_remove_child_institution_options

        """
        pass

    def test_api_v1_super_user_remove_child_institution_post(self):
        """Test case for api_v1_super_user_remove_child_institution_post

        """
        pass

    def test_api_v1_super_user_update_institute_user_institution_id_user_id_options(self):
        """Test case for api_v1_super_user_update_institute_user_institution_id_user_id_options

        """
        pass

    def test_api_v1_super_user_update_institute_user_institution_id_user_id_put(self):
        """Test case for api_v1_super_user_update_institute_user_institution_id_user_id_put

        """
        pass

    def test_api_v1_super_user_update_user_status_options(self):
        """Test case for api_v1_super_user_update_user_status_options

        """
        pass

    def test_api_v1_super_user_update_user_status_post(self):
        """Test case for api_v1_super_user_update_user_status_post

        """
        pass

    def test_sms_get(self):
        """Test case for sms_get

        """
        pass

    def test_sms_post(self):
        """Test case for sms_post

        """
        pass

    def test_ws_notification_userid_get(self):
        """Test case for ws_notification_userid_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
